services:
  database:
    profiles:
      - local
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local
